version: '3.5'
services:
  web:
    build:
      context: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
    ports:
      - 3001:3000
    env_file: .env
    stdin_open: true
    tty: true

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

volumes:
  bundle-cache: null