apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "chart.fullname" . }}-cronjob"
  labels:
    app.kubernetes.io/name: "{{ include "chart.fullname" . }}-cronjob"
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "0 0 */1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ include "chart.fullname" . }}-backup"
            image: busybox
            args:
            - /bin/sh
            - -c
            - wget http://{{ include "chart.name" . }}-web-service/api/backup
          restartPolicy: OnFailure